### ISSUE TITLE
Bug Report: Extra backlash added before opening bracket

### ISSUE THREAD

**Issue by Zhruang** [bkis/obsidian-hard-breaks#4]
Whenever I use the command to force hard breaks, it adds one backlash to each opening bracket in the document, which turns the links in the documents unparsed.

Version of the plugin: 0.0.3
Obsidian version: v0.15.9
Platform: MacOS 12.4

**Comment by bkis** [comment]
Oof.. Not good. Thank you for writing an issue!  
On monday I'll try to replicate and fix this 👍

**Comment by bkis** [comment]
I just tried it. This is the Markdown source I used:

```md
[link](http://link.com)

foo [link](http://link.com)

foo [link](http://link.com) bar

- [link](http://link.com) foo
- foo [link](http://link.com) bar

foo
bar
```

Using the plugin's command and backslashes (for better visibility), this was the result:

```md
[link](http://link.com)

foo [link](http://link.com)

foo [link](http://link.com) bar

*   [link](http://link.com) foo
*   foo [link](http://link.com) bar

foo\
bar
```

So it actually only added **one** hard line break after the last "foo" - which is correct. What it also did was converting the list items I created with a `-` to ones with a `*` *and then added two whitespaces after them*. This is something the library I used does ([remark](https://github.com/remarkjs/remark)), as it parses the whole Markdown, and then makes it a string again - applying what it thinks it the best way to write things (`*` instead of `-`).

If this is good or not is debatable, but it looks like I cannot reproduce your problem. I can't even imagine how and why this should happen. Did you, by any chance, make any further observations by now?

Thanks again!

**Comment by bkis** [comment]
Oh, i see, you were using version `0.0.3` - would you mind updating to `0.1.0` just to check? I bumped the version to mark the manifestation of the first release I considered stable, but actually there was only some code cleanup before the release. `0.0.3` *should* work.

EDIT: I just tried `0.0.3` myself - same result. I'm on Pop_OS! 22.04 btw... but this should definitely work on MacOS. Could you please deactivate all other community plugins and try again? I suspect some other plugin might interfere or vice versa.

**Comment by Zhruang** [comment]
Hi, the code you posted above works perfectly. Yet, I met the aforementioned issue when the document contains the obsidian bi-directional link `[[]]` and just an arbitrary pair of brackets (as can happen in academic writing or other cases). Would you be kind enough to test a piece of code that I use:
```
[[test]]
“[Danny] is a boy.”
```
Thanks!

**Comment by bkis** [comment]
I see... it becomes

```md
\[\[test]]\
“\[Danny] is a boy.”
```

I never used Obsidian's `[[links]]` link format - so I didn't notice. This happens because remark cannot parse these `[[links]]` as they're not valid Markdown. I'll see if I can find a remark plugin to make it recognize them!

EDIT: Or write one :eyes: 

EDIT 2: Found something [here](https://www.npmjs.com/package/remark-wiki-link). Will try it as soon as I can!

**Comment by Zhruang** [comment]
Thank you so much in advance! By the way, this plugin is indeed something that I have been waiting for, so kudos to you!
