### ISSUE TITLE
Functionality replicated in Linter

### ISSUE THREAD

**Issue by Calorion** [bkis/obsidian-hard-breaks#6]
Just FYI, the functionality in this plugin is replicated in the "[Two spaces between lines with content](https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#two-spaces-between-lines-with-content)" rule in the [Linter](https://github.com/platers/obsidian-linter) plugin, which has a lot of other functionality besides.

**Comment by bkis** [comment]
Thank you for reaching out and pointing me to this! I shouldn't maintain an obsolete plugin, so I think you have a valid point. I looked into the linter plugin and like it a lot. Very nice idea - and carried out quite nicely. That said, I still want to keep this plugin alive for the following reasons:

1. I think that even knowing the linter plugin, the hard-breaks plugin still holds a certain value, because the two are having very different goals while sharing functionality. The linter plugin is for defining an overall set of rules to format Markdown source that is to be applied all at once. I don't see functionality to trigger different rulesets individually, so to really replicate the (very special) functionality concerning the hard breaks without touching anything else, you'd have to configure the linter plugin to do *only that*. Personally, I'd say the two could be used side-by-side very nicely. The linter for enforcing general formatting rules, the hard breaks plugin only as a scalpel for that special need of hard breaks.
2. Many people seem to prefer the backslash (`\`) notation of hard breaks, as those are *visible*. With a specialized plugin like this one, you have a choice of what's used.
3. I can imagine there'll be ideas to extend the functionality of this plugin in the future. Like a certain shortcut for a hard break (<kbd>Shift</kbd>+<kbd>↲</kbd> ??), creating hard breaks as you type (not easy to implement because of the constrained contexts we want hard breaks to be allowed in), ...

So again, thanks for this hint! I'm gonna try to integrate the linter plugin into my workflow, I like it! But for now, I'll let the heard-breaks plugin co-exist with it.

**Comment by Calorion** [comment]
1. Linter definitely allows using only one Rule; indeed some rules conflict with each other. I think they are all off by default. 
2. Excellent point. My purpose was not necessarily to tell you to deprecate this plugin; Linter is complicated and if you don't need its other functionality this could be better. I just wanted to let you and others know. 
3. This sounds like a great idea. Can't wait!

**Comment by bkis** [comment]
1. I know, maybe I wasn't clear on that... As far as I understand the linter plugin, I cannot define multiple "profiles" or "rulesets" so it's either "lint all the stuff i want you to lint" (the actual purpose of the plugin) or "only do hard breaks" (which would replace the hard breaks plugin but then the linter doesn't do anything else). So what I'm saying is - if you use both, you could have both :)

Anyway, thanks for putting thought into this!
